config/routes.rb
Rails.application.routes.draw do

  resources :contents
    get '/myProfile' => 'profiles#my_profile'
    resources :profiles
    resources :user_publications
    resources :people_projects
    devise_for :users, :controllers => {:registrations => "registrations"} do
        get '/users/sign_out' => 'devise/sessions#destroy'

    end

    scope '/admin' do
        scope '/members' do
            match '/update/:id', to: 'admin#update_member', :as => :admin_update_member, via: [:patch, :put, :post]
            match '/edit/:id' => 'admin#edit_member', :as => :admin_edit_member, via: [:get]
        end
        match '/members' => 'admin#members', :as => :admin_members, via: [:get]
        
  
    end

    resources :user_contexts
    resources :contexts
    resources :add_users
    resources :sponsors
    
    resources :people_projects
    resources :publications
    resources :projects
    resources :journals
    resources :news
    root "news#index"

    resources :news

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
    @user = current_user
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
    @user = current_user
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    respond_to do |format|
      if @content.save
        format.html { redirect_to myProfile_path, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to myProfile_path, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to myProfile_path, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:userid, :post)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @content.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h4>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.hidden_field :userid, :value => current_user.id %>
  </div>
  <div class="form-group">
    <%= f.label :post, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :post, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div class="page-header">
  <%#= link_to contents_path, class: 'btn btn-default' do %>
    <!-- <span class="glyphicon glyphicon-list-alt"></span>
    Back -->
  <%# end %>
  <%= link_to @content, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing content</h1>
</div>

<%= render 'form' %>

app/views/contents/index.html.erb
<div class="page-header">
  <%#= link_to new_content_path, class: 'btn btn-primary' do %>
    <!-- <span class="glyphicon glyphicon-plus"></span>
    New Content -->
  <%# end %>
  <h1>Listing contents</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Userid</th>
            <th>Post</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @contents) do |content| %>
            <td><%= content.userid %></td>
            <td><%= content.post %></td>
            <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contents/new.html.erb
<div class="page-header">
  <%#= link_to contents_path, class: 'btn btn-default' do %>
    <!-- <span class="glyphicon glyphicon-list-alt"></span>
    Back -->
  <%# end %>
  <h1>New content</h1>
</div>

<%= render 'form' %>

app/views/contents/show.html.erb
<div class="page-header">
  <%#= link_to contents_path, class: 'btn btn-default' do %>
    <!-- <span class="glyphicon glyphicon-list-alt"></span>
    Back -->
  <%# end %>
  <%= link_to edit_content_path(@content), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show content</h1>
</div>

<dl class="dl-horizontal">
  <dt>Userid:</dt>
  <dd><%= @content.userid %></dd>

  <dt>Post:</dt>
  <dd><%= @content.post %></dd>

</dl>