config/routes.rb
Rails.application.routes.draw do

  resources :contents
    get '/myProfile' => 'profiles#my_profile'
    resources :profiles
    resources :user_publications
    resources :people_projects
    devise_for :users, :controllers => {:registrations => "registrations"} do
        get '/users/sign_out' => 'devise/sessions#destroy'

    end

    scope '/admin' do
        scope '/members' do
            match '/update/:id', to: 'admin#update_member', :as => :admin_update_member, via: [:patch, :put, :post]
            match '/edit/:id' => 'admin#edit_member', :as => :admin_edit_member, via: [:get]
        end
        match '/members' => 'admin#members', :as => :admin_members, via: [:get]
        
  
    end

    resources :user_contexts
    resources :contexts
    resources :add_users
    resources :sponsors
    
    resources :people_projects
    resources :publications
    resources :projects
    resources :journals
    resources :news
    root "news#index"

    resources :news

end

app/models/publication.rb
class Publication < ActiveRecord::Base
    validates :title, presence: true
    validates :year, presence: true
    validates :page, presence: true
    validates :pageend, presence: true
    validates :volume, presence: true
    validates :journal_id, presence: true

    validates :page, numericality: {only_integer: true, greater_than: 0}
    validates :pageend, numericality: {only_integer: true, greater_than: 0}
    validates :volume, numericality: {only_integer: true, greater_than: 0}
    validates :year, numericality: {only_integer: true, less_than_or_equal_to: Date.today.year.to_i}

    belongs_to :journal
    has_many :user_publications
    has_many :users, through: :user_publications

    has_attached_file :document
    validates_attachment :document, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}



    def self.create_with_user(publication_params, user_params)
        publication = Publication.new(publication_params)
        begin
            Project.transaction do
                publication = Publication.create!(publication_params)
                UserPublication.transaction do

                    if (user_params.any?)
                        user_params[:user_id].each do |user_id|
                            user = User.find_by_id(user_id)
                            if (user.nil?)
                                ActiveRecord::Rollback
                                publication.errors.add(:notice, "Error in save data")
                                return publication
                            end
                            begin
                                UserPublication.create!([user_id: user.id, publication_id: publication.id])
                            rescue
                                publication.errors.add(:notice, "Error in save data")
                                ActiveRecord::Rollback
                                return publication
                            end
                        end
                    end
                end
            end
        rescue
            ActiveRecord::Rollback
            publication.errors.add(:notice, "Error in save data")
            return publication
        end
        return publication
    end


    def update_with_user(publication_params, user_params)
        begin
            Publication.transaction do
                UserPublication.transaction do
                    if not self.update(publication_params)
                        return false
                    end


                    user_publications = UserPublication.where(publication_id: self.id)
                    if not user_publications.nil?
                        user_publications.delete_all
                    end

                    if (user_params.any?)
                        user_params[:user_id].each do |user_id|

                            # byebug

                            user = User.find_by_id(user_id)
                            if (user.nil?)
                                ActiveRecord::Rollback
                                self.errors.add(:users, "user dosn't exist")
                                return false
                            end
                            UserPublication.create!([user_id: user_id, publication_id: self.id])
                            # byebug

                        end
                    end
                end
            end
        rescue
            self.errors.add(:notice, "error")
            return false
        end
        return true
        # byebug
    end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
    before_action :set_publication, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    # GET /publications
    # GET /publications.json
    def index
        #@publications = Publication.all
        @per_page=5
                if params.has_key?(:title)
                    @publications = Publication.where('title like ?', '%'+params[:title].to_s+'%').
                            paginate(:page => params[:page], per_page: @per_page)
                else
                    @publications = Publication.all.paginate(:page => params[:page], per_page: @per_page)
                end
    end

    # GET /publications/1
    # GET /publications/1.json
    def show
        @profiles = @publication.users
    end

    # GET /publications/new
    def new
        @publication = Publication.new
        @journals = Journal.all
        @users = User.all
    end

    # GET /publications/1/edit
    def edit
        @journals = Journal.all
        @users = User.all
    end

    # POST /publications
    # POST /publications.json
    def create
        @publication = Publication.create_with_user(publication_params, user_params)
        respond_to do |format|
            if @publication.save
                format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
                format.json { render :show, status: :created, location: @publication }
            else
                @journals = Journal.all
                @users = User.all
                format.html { render :new }
                format.json { render json: @publication.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /publications/1
    # PATCH/PUT /publications/1.json
    def update
        respond_to do |format|
            if @publication.update_with_user(publication_params, user_params)
                format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
                format.json { render :show, status: :ok, location: @publication }
            else
                @journals = Journal.all
                @users = User.all
                format.html { render :edit }
                format.json { render json: @publication.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /publications/1
    # DELETE /publications/1.json
    def destroy
        #byebug
        @publication.destroy
        respond_to do |format|
            format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
        @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
        params.require(:publication).permit(:title, :year, :volume, :page, :pageend, :document, :journal_id)
    end

    def user_params
        if (not params[:user].nil?)
            params.require(:user).permit(:user_id => [])
        else
            return []
        end

    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
    def is_owner (publication)
        return !current_user.nil? && !current_user.publications.nil? && current_user.publications.collect { |p| p.id }.include?(publication.id)
    end
end

app/views/publications/_form.html.erb
<%= form_for(@publication, html: {class: "form-horizontal", role: "form"}) do |f| %>
    <% if @publication.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h4>

          <ul>
            <% @publication.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :year, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :year, class: "form-control" %>
      </div>
    </div><div class="form-group">
      <%= f.label :volume, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :volume, class: "form-control" %>
      </div>
    </div>

    <div class="row">
    <%= f.label :page , 'Page from:', class: "col-sm-2 control-label" %>
      
    <div class="form-group col-xs-4">
      <div class="col-sm-12">
        <%= f.number_field :page, class: "form-control", placeholder: "from" %>
      </div>
    </div>

    <%= f.label :pageend, ' to:', class: "col-sm-2 control-label" %>
    <div class="form-group col-xs-4">

      <div class="col-sm-12">
        <%= f.number_field :pageend, class: "form-control", placeholder: "to" %>
      </div>
    </div>

    </div>


    <div class="form-group">
      <label class="col-sm-2 control-label"> Authors </label>
      <div class="col-sm-10">
        <select name="user[user_id][]" class="selectpicker form-control" multiple>
          <% @users.each do |user| %>
              <option value="<%= user.id %>"><%= user.email %></option>
          <% end %>
        </select>

      </div>
    </div>



<!-- 
    <div class="form-group">
                              <label class="control-label" >آپلود گزارش</label>
                              <%#= f.file_field :document ,class: "form-control spinner" %>
                              <!-- <input type="password" class="form-control spinner" placeholder="Password"> -->
                         <!--   </div> -->
                            

    <div class="form-group">
      <%= f.label :journal_id, 'Journal_Confrence', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select(:journal_id, @journals.map { |p| [p.name, p.id] },{prompt: 'Select a Journal_Confrence'}, { class: 'form-control'}) %>
      </div>
    </div> 


    <div class="form-group">
    <label class="col-sm-2 control-label"> Documents </label>
      
      <div class="col-sm-10 fileinput fileinput-new" data-provides="fileinput">
          
          <div>
              <span class="btn default btn-file">
                  <span class="fileinput-new"> Publication upload </span>
                  <span class="fileinput-exists"> setting </span>
                  <%= f.file_field :document, as: :file %>
              </span>
              <a href="javascript:;" class="btn default fileinput-exists" data-dismiss="fileinput">
                  Remove </a>
          </div>
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
<% end %>



<script>
  $(document).ready(function () {
    <% @user_ids = [] %>
    <%
    @publication.users.each do |user|
    @user_ids.push(user.id)
    end
    %>
    $('.selectpicker').val(<%= @user_ids %>);
    $('.selectpicker').selectpicker('refresh');
  });
</script>

app/views/publications/_search_form.erb
<form action="/publications">
	Publication Title:<br>
	<input type="text" name="title">
	<br><br>
	<input type="submit" value="publication search">
</form>

app/views/publications/edit.html.erb
<div class="page-header">
  <%= link_to publications_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @publication, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing publication</h1>
</div>

<%= render 'form' %>

app/views/publications/index.html.erb
<div class="page-header">
  <%= link_to new_publication_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Publication
  <% end %>
  <h1>Listing publications</h1>
</div>

<%= render 'publications/search_form' %>


<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Volume</th>
            <th colspan="2">Pages</th>
            <th>Journal_Confrence</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @publications) do |publication| %>
            <td><%= publication.title %></td>
            <td><%= publication.year %></td>
            <td><%= publication.pageend %></td>
            <td><%= publication.page %></td>
            <td><%= publication.volume %></td>
            <td><%= publication.journal.name %></td>
            <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/publications/new.html.erb
<div class="page-header">
  <%= link_to publications_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New publication</h1>
</div>

<%= render 'form' %>

app/views/publications/show.html.erb
<div class="page-header">
  <%= link_to publications_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_publication_path(@publication), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show publication</h1>
</div>


<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @publication.title %></dd>

  <dt>Year:</dt>
  <dd><%= @publication.year %></dd>

  <dt>Page:</dt>
  <dd><%= @publication.page %></dd>

  <dt>Pageend:</dt>
  <dd><%= @publication.pageend %></dd>  

  <dt>Journal_Confrence:</dt>
  <dd><%= @publication.journal.name %></dd>

  <dt>document:</dt>
  <dd><%= link_to "My document", @publication.document.url%></dd>



  <dt>Users:</dt>
  <dd>
    <% @profiles.each do |profile|%>
        <%= link_to( profile.email, :controller => "profiles", :action => "show", :id => profile.id) %>
    <%end%>
  </dd>
</dl>