config/routes.rb
Rails.application.routes.draw do

  resources :contents
    get '/myProfile' => 'profiles#my_profile'
    resources :profiles
    resources :user_publications
    resources :people_projects
    devise_for :users, :controllers => {:registrations => "registrations"} do
        get '/users/sign_out' => 'devise/sessions#destroy'

    end

    scope '/admin' do
        scope '/members' do
            match '/update/:id', to: 'admin#update_member', :as => :admin_update_member, via: [:patch, :put, :post]
            match '/edit/:id' => 'admin#edit_member', :as => :admin_edit_member, via: [:get]
        end
        match '/members' => 'admin#members', :as => :admin_members, via: [:get]
        
  
    end

    resources :user_contexts
    resources :contexts
    resources :add_users
    resources :sponsors
    
    resources :people_projects
    resources :publications
    resources :projects
    resources :journals
    resources :news
    root "news#index"

    resources :news

end

app/models/project.rb
class Project < ActiveRecord::Base
    validates :title, presence: true
    validates :start_date, presence: true
    validates :end_time, presence: true
    validates :sponsor_id, presence: true
    validates :goal, presence: true
    validate :end_time_validate

    belongs_to :sponsor
    has_many :people_projects
    has_many :users, through: :people_projects

    def self.create_with_user(project_params, user_params)
        project = Project.new(project_params)
        begin
            Project.transaction do
                project = Project.create!(project_params)
                PeopleProject.transaction do

                    if (user_params.any?)
                        user_params[:user_id].each do |user_id|
                            user = User.find_by_id(user_id)
                            if (user.nil?)
                                ActiveRecord::Rollback
                                flash[:notice] = "error in save data"
                                return project
                            end
                            begin
                                PeopleProject.create!([user_id: user.id, project_id: project.id])
                            rescue
                                project.errors.add(:notice, "Error in save data")
                                ActiveRecord::Rollback
                                return project
                            end
                        end
                    end
                end
            end
        rescue
            ActiveRecord::Rollback
            project.errors.add(:notice, "Error in save data")
            return project
        end
        return project
    end

    def update_with_user(project_params, user_params)
        Project.transaction do
            PeopleProject.transaction do

                if not self.update(project_params)
                    return false
                end


                people_projects = PeopleProject.where(project_id: self.id)
                if not people_projects.nil?
                    people_projects.delete_all
                end

                if (user_params.any?)
                    user_params[:user_id].each do |user_id|

                        # byebug
                        user = User.find_by_id(user_id)
                        if (user.nil?)
                            raise ActiveRecord::Rollback
                        end
                        PeopleProject.create!([user_id: user_id, project_id: self.id])
                        # byebug

                    end
                end

            end
        end
        # byebug
    end

    def destroy_with_dependencies
        Project.transaction do
            PeopleProject.transaction do

                people_projects = PeopleProject.where(project_id: self.id)
                if not people_projects.nil?
                    people_projects.delete_all
                end

                self.delete
            end
        end
    end

    # private
    def end_time_validate
        # byebug
        if start_date.presence && end_time.presence && start_date >= end_time

            errors.add(:end_time, "must be greater than start date")
        end
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_dependency, only: [:new, :edit]

    # GET /projects
    # GET /projects.json
    def index
        @projects = Project.all
    end

    # GET /projects/1
    # GET /projects/1.json
    def show
        @profiles = @project.users
    end

    # GET /projects/new
    def new
        @project = Project.new
    end

    # GET /projects/1/edit
    def edit
    end
    # POST /projects
    # POST /projects.json
    def create
        @project = Project.create_with_user(project_params, user_params)

        respond_to do |format|
            if @project.save
                format.html { redirect_to @project, notice: 'Project was successfully created.' }
                format.json { render :show, status: :created, location: @project }
            else
                @users = User.all
                @sponsors = Sponsor.all
                format.html { render :new }
                format.json { render json: @project.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /projects/1
    # PATCH/PUT /projects/1.json
    def update
        respond_to do |format|
            if @project.update_with_user(project_params, user_params)
                format.html { redirect_to @project, notice: 'Project was successfully updated.' }
                format.json { render :show, status: :ok, location: @project }
            else
                @users = User.all
                @sponsors = Sponsor.all
                format.html { render :edit }
                format.json { render json: @project.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /projects/1
    # DELETE /projects/1.json
    def destroy
        @project.destroy_with_dependencies
        respond_to do |format|
            format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    def set_dependency
        @users = User.all
        @sponsors = Sponsor.all
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
        @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
        params.require(:project).permit(:title, :goal, :start_date, :end_time, :sponsor_id)
    end
    
    def user_params
        if (not params[:user].nil?)
            params.require(:user).permit(:user_id => [])
        else
            return []
        end

    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def is_owner (project)
        return !current_user.nil? && !current_user.projects.nil? && current_user.projects.collect { |p| p.id }.include?(project.id)
    end
end

app/views/projects/_form.html.erb
<%= form_for(@project, html: {class: "form-horizontal form-bordered form-row-stripped", role: "form"}) do |f| %>
    <% if @project.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>

            <ul>
                <% @project.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="form-body">

        <div class="form-group">
            <%= f.label :title, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.text_field :title, class: "form-control input-circle-right", required: 'true', autofocus: 'true' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :goal, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.text_area :goal, class: "form-control", required: 'true' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :start_date, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.date_select :start_date, class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :end_time, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.date_select :end_time, class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :sponsor_id, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.select :sponsor_id,
                             options_for_select(@sponsors.map { |p| [p.name, p.id] }),
                             {prompt: "Select one sponsor"}, {required: 'true', prompt: "Select one sponsor", class: 'form-control'} %>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"> users </label>
            <div class="col-sm-10">
                <select name="user[user_id][]" class="selectpicker form-control" multiple>
                    <% @users.each do |user| %>
                        <option value="<%= user.id %>"><%= user.email %></option>
                    <% end %>
                </select>

            </div>
        </div>
        <div class=" form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: "btn btn-primary" %>
            </div>
        </div>

    </div>
<% end %>

<script>
    $(document).ready(function () {
        <% @user_ids = [] %>
        <%
        @project.users.each do |user|
        @user_ids.push(user.id)
        end
        %>
        $('.selectpicker').val(<%= @user_ids %>);
        $('.selectpicker').selectpicker('refresh');
    });
</script>

app/views/projects/edit.html.erb
<div class="portlet box blue">
    <div class="portlet-title">

        <div class="caption">

            <div class="caption">
                <i class="icon-speech"></i>
                <span class="caption-subject bold uppercase">Editing project</span>
            </div>
        </div>
        <div class="actions">
            <%= link_to projects_path, class: 'btn btn-circle btn-default' do %>
                <span class="glyphicon glyphicon-list-alt"></span>
                Back
            <% end %>

            <%= link_to @project, class: 'btn btn-circle btn-primary' do %>
                <span class="glyphicon glyphicon-info-sign"></span>
                Show
            <% end %>
            <a href="javascript:;" class="btn btn-circle btn-icon-only btn-default fullscreen" data-original-title="" title=""> </a>

        </div>
    </div>
    <div class="portlet-body">

        <%= render 'form' %>

    </div>
</div>

app/views/projects/index.html.erb
<!--<div class="row">
    <%#= link_to new_project_path, class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-plus"></span>
        New Project
    <%# end %>
    <br/><br/>
     
    <%# @projects.each do |project| %>
        <div class="col-md-4">
            <div class="portlet light">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-speech"></i>
                        <span class="caption-subject bold uppercase font-green-sharp"> <%#= project.title %></span>
                    </div>
                    <div class="actions">
                        <%#= link_to edit_project_path(project), class: "btn btn-circle btn-default" do %>
                            <i class="fa fa-pencil"></i> Edit
                        <%# end %>
                        <%#= link_to project, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-circle btn-default red-sunglo" do %>
                            <i class="fa fa-plus"></i> Delete
                        <%# end %>
                        <a href="javascript:;" class="btn btn-circle btn-icon-only btn-default fullscreen" data-original-title="" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body" style="height: auto;">
                    <div class="scroller" style="height:300px"
                         data-rail-visible="1" data-rail-color="yellow" data-handle-color="#a1b2bd">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="col-sm-12 "><strong>Sponsor Name :</strong></label>
                                <div class="col-sm-12">
                                    <%#= project.sponsor.name %>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12"><strong>Goal :</strong></label>
                                <div class="col-sm-12">
                                    <%#= project.goal %>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-12"><strong>Start Date</strong></label>
                                <div class="col-sm-12">
                                    <%#= project.start_date %>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12 "><strong>Sponsor Name :</strong></label>
                                <div class="col-sm-12">
                                    <%#= project.end_time %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <%# end %> 
-->

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Sponsor Name</th>
            <th>Goal</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th></th>
            <th></th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @projects) do |pj| %>
        <td><%= pj.title %></td>
        <td><%= pj.sponsor.name %></td>
        <td><%= pj.goal %></td>
        <td><%= pj.start_date %></td>
        <td><%= pj.end_time %></td>
        <td><%= link_to 'Show', pj %></td>
        <td><%= link_to 'Edit', edit_project_path(pj) %></td>
        <td><%= link_to 'Destroy', pj, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div> 

<!-- </div> -->

app/views/projects/new.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New project</h1>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_project_path(@project), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show project</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @project.title %></dd>

  <dt>Goal:</dt>
  <dd><%= @project.goal %></dd>

  <dt>Start date:</dt>
  <dd><%= @project.start_date %></dd>

  <dt>End time:</dt>
  <dd><%= @project.end_time %></dd>

  <dt>Sponsor:</dt>
  <dd><%= @project.sponsor.name %></dd>

  <dt>Users :</dt>
  <dd>
    <% @profiles.each do |profile|%>
    <%= link_to( profile.email, :controller => "profiles", :action => "show", :id => profile.id) %>
    <%end%>
  </dd>

</dl>