config/routes.rb
Rails.application.routes.draw do

  resources :contents
    get '/myProfile' => 'profiles#my_profile'
    resources :profiles
    resources :user_publications
    resources :people_projects
    devise_for :users, :controllers => {:registrations => "registrations"} do
        get '/users/sign_out' => 'devise/sessions#destroy'

    end

    scope '/admin' do
        scope '/members' do
            match '/update/:id', to: 'admin#update_member', :as => :admin_update_member, via: [:patch, :put, :post]
            match '/edit/:id' => 'admin#edit_member', :as => :admin_edit_member, via: [:get]
        end
        match '/members' => 'admin#members', :as => :admin_members, via: [:get]
        
  
    end

    resources :user_contexts
    resources :contexts
    resources :add_users
    resources :sponsors
    
    resources :people_projects
    resources :publications
    resources :projects
    resources :journals
    resources :news
    root "news#index"

    resources :news

end

app/models/journal.rb
class Journal < ActiveRecord::Base
    validates :name , presence: true
    validates :name , uniqueness: {case_sensitive: false}

    has_many :publications
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:name)
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @journal.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h4>

      <ul>
      <% @journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/journals/edit.html.erb
<div class="page-header">
  <%= link_to journals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @journal, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing journal</h1>
</div>

<%= render 'form' %>

app/views/journals/index.html.erb
<div class="page-header">
  <%= link_to new_journal_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Journal
  <% end %>
  <h1>Listing journals</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @journals) do |journal| %>
            <td><%= journal.name %></td>
            <td><%= link_to 'Show', journal %></td>
        <td><%= link_to 'Edit', edit_journal_path(journal) %></td>
        <td><%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/journals/new.html.erb
<div class="page-header">
  <%= link_to journals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Project</h1>
</div>

<%= render 'form' %>

app/views/journals/show.html.erb
<div class="page-header">
  <%= link_to journals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_journal_path(@journal), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show journal</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @journal.name %></dd>

</dl>